### ISSUE TITLE
cypthon compile error when install from source using latest version

### ISSUE THREAD

**Issue by zengxy** [dmlc/dgl#488]
## 🐛 Bug

I'm tring to install from srouce using the lastest version of master `00fc680aae15c4e463c8efc1218a4da143fedb8c`

And I follow the steps in https://docs.dgl.ai/install/index.html#install-from-source

At the last step `python setup.py install`, something got type not import error 
```
Compiling dgl/_ffi/_cython/core.pyx because it depends on dgl/_ffi/_cython/base.pxi.
[1/1] Cythonizing dgl/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                               const dgl_index_t *shape,
                               int ndim,
                               int dtype_code,
                               int dtype_bits,
                               int dtype_lanes,
                               bool is_create,
                              ^
------------------------------------------------------------

dgl/_ffi/_cython/./base.pxi:103:31: 'bool' is not a type identifier

Error compiling Cython file:
------------------------------------------------------------
...
                               int ndim,
                               int dtype_code,
                               int dtype_bits,
                               int dtype_lanes,
                               bool is_create,
                               DGLArrayHandle* out)
                              ^
------------------------------------------------------------

dgl/_ffi/_cython/./base.pxi:104:31: 'DGLArrayHandle' is not a type identifier

```

I tried to import it myself in `base.pxi` by adding
```python
from libcpp cimport bool

ctypedef DLTensor DGLArray
ctypedef DGLArray* DGLArrayHandle
```
Passing this file `core.pyx` but got error in `ndarray.pxi`
```
Compiling dgl/_ffi/_cython/core.pyx because it changed.
[1/1] Cythonizing dgl/_ffi/_cython/core.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from ..runtime_ctypes import DGLArrayHandle
^
------------------------------------------------------------

dgl/_ffi/_cython/./ndarray.pxi:1:0: Compiler crash in AnalyseExpressionsTransform

File 'Nodes.py', line 432, in analyse_expressions: StatListNode(core.pyx:1:0)
File 'Nodes.py', line 432, in analyse_expressions: StatListNode(ndarray.pxi:1:0)
File 'Nodes.py', line 7971, in analyse_expressions: FromImportStatNode(ndarray.pxi:1:0,
    interned_items = [...]/0,
    items = [...]/1)

Compiler crash traceback from this point on:
  File "/usr/local/lib/python3.6/dist-packages/Cython/Compiler/Nodes.py", line 7971, in analyse_expressions
    if (entry.is_type and entry.type.name == name
  File "/usr/local/lib/python3.6/dist-packages/Cython/Compiler/PyrexTypes.py", line 549, in __getattr__
    return getattr(self.typedef_base_type, name)
AttributeError: 'CPtrType' object has no attribute 'name'
```

I'm not that familiar with cython, and dont know how to deal with it.

As a contrast, I also tried to build on tag `v0.2`，and everything went well.

My env are `ubuntu 18.04`,  `Cython 0.28.4`, `gcc 7.3.0`

Could anyone help to fix it?

**Comment by BarclayII** [comment]
Fixed.  Please check.

**Comment by zengxy** [comment]
Thank you ! I can build it now.
