### ISSUE TITLE
Fails to build with PyTorch-2.14.0

### ISSUE THREAD

**Issue by yurivict** [dmlc/dgl#7934]
```
In file included from /wrkdirs/usr/ports/math/dgl/work/dgl-2.4.0/dgl_sparse/src/reduction.cc:10:
In file included from /wrkdirs/usr/ports/math/dgl/work/dgl-2.4.0/dgl_sparse/include/sparse/elementwise_op.h:9:
In file included from /wrkdirs/usr/ports/math/dgl/work/dgl-2.4.0/dgl_sparse/include/sparse/sparse_matrix.h:13:
In file included from /wrkdirs/usr/ports/math/dgl/work/dgl-2.4.0/dgl_sparse/include/sparse/sparse_format.h:13:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/torch/custom_class.h:4:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/ATen/core/builtin_function.h:4:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/ATen/core/function.h:4:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/ATen/core/function_schema.h:6:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/ATen/core/jit_type.h:5:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/ATen/core/jit_type_base.h:11:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/c10/core/SymInt.h:4:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/c10/core/SymBool.h:5:
In file included from /usr/local/lib/python3.12/site-packages/torch/include/c10/core/SymNodeImpl.h:8:
/usr/local/lib/python3.12/site-packages/torch/include/c10/util/intrusive_ptr.h:775:27: error: no type named 'strong_ordering' in namespace 'std'
  775 | [[nodiscard]] inline std::strong_ordering operator<=>(
      |                      ~~~~~^
/usr/local/lib/python3.12/site-packages/torch/include/c10/util/intrusive_ptr.h:775:43: error: 'operator<=' cannot be the name of a variable or data member
  775 | [[nodiscard]] inline std::strong_ordering operator<=>(
      | /wrkdirs/usr/ports/math/dgl/work/dgl-2.4.0/dgl_sparse/src/spmm.cc                                          ^
/usr/local/lib/python3.12/site-packages/torch/include/c10/util/intrusive_ptr.h:775:53: error: expected ';' after top level declarator
  775 | [[nodiscard]] inline std::strong_ordering operator<=>(
      |                                                     ^
```

Version: 2.4.0
FreeBSD 15.1
