### PR TITLE
[Bugfix] 'const size_t' (aka 'const unsigned long') is ambiguous on MacOS

### PR DESCRIPTION
**Pull request by aksnzhy**
## Description
This small pr fix the compilation error in Mac OS X.

### CODE REVIEW

**Comment by jermainewang** [comment]
Could you post the error message here?

**Comment by zheng-da** [comment]
I got the same compilation error in Mac.

**Comment by jermainewang** [comment]
I see what happened. This bug is introduced in #359 (@GaiYu0 be aware of this subtlety) . Before that, we were using `int`.  I feel we need a macos ci to avoid such thing to happened again.
