### ISSUE TITLE
DistDGL communication bug

### ISSUE THREAD

**Issue by bioannidis** [dmlc/dgl#3604]
## 🐛 Bug

Hello team. Our code for distributed training does not proceed after the following call.

**_th.distributed.init_process_group(backend=self.backend)_**
There is no error message the code just hangs there.

This happens if we use the latest DGL nightly build version.
Da mentioned it might be related to the change in the communication in DistDGL.

If I use the following version there is no problem.
pip3 install --pre dgl-cu110==0.8a211206 -f https://data.dgl.ai/wheels-test/repo.html

**Comment by VoVAllen** [comment]
Which backend are you using?

**Comment by VoVAllen** [comment]
Also are you using GPU training?

**Comment by bioannidis** [comment]
Yes I am using GPU training. The cluster has 2 machines and the backend is gloo

**Comment by bioannidis** [comment]
The machines are p4dns

**Comment by VoVAllen** [comment]
I'll test it tommorow

**Comment by VoVAllen** [comment]
I tested with 4 g4dn.8xlarge with one GPU each on ogb-product dataset by https://github.com/dmlc/dgl/blob/master/examples/pytorch/graphsage/experimental/train_dist.py.
And it works normally.

Did you have the same problem with other instance type (for example g4dn) or does it work well with dgl 0.7.2?

**Comment by classicsong** [comment]
After updating dgl to the newest nightly build. I got this error:
```
 File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
  File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
      File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/dataloading/dataloader.py", line 256, in _prefetch_for_subgraph
return [recursive_apply(v, fn, *args, **kwargs) for v in data]
  File "/home/xiangsx/.local/lib/python3.7/site-packages/dgl/utils/internal.py", line 921, in recursive_apply
            node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,node_feats, subg._node_frames, subg.ntypes, dataloader.graph.get_node_storage,


AttributeErrorAttributeErrorAttributeError: : : 'DistGraph' object has no attribute 'get_node_storage''DistGraph' object has no attribute 'get_node_storage''DistGraph' object has no attribute 'get_node_storage'

```

**Comment by jermainewang** [comment]
The hanging bug should be resolved in #4036 .
